Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Blog.ArticleCategory;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {

        }

        public RedirectToPageResult OnPost(CreateArticleCategory command)
        {
            _articleCategoryApplication.Create(command);
           return RedirectToPage("./list");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.ArticleCategory;
using Reter.Application.Contracts.Blog.ArticleCategory.Commands;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public EditArticleCategory ArticleCategory { get; set; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(string id)
        {
            ArticleCategory = _articleCategoryApplication.Get(id);
        }

        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Edit(ArticleCategory);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/List.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.ArticleCategory;
using Reter.Domain.Blog.ArticleCategoryAgg;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication= articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostRemove(string id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./list");
        }

        public RedirectToPageResult OnPostActivate(string id)
        {
            _articleCategoryApplication.Activate(id);
            return RedirectToPage("./list");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Reter.Application.Contracts.Blog.Article;
using Reter.Application.Contracts.Blog.Article.Commands;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> ArticleCategories { get; set; }

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication,
            IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }


        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List().Select(x => new SelectListItem(x.Title, x.Id))
                .ToList();
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            _articleApplication.Create(command);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Reter.Application.Contracts.Blog.Article;
using Reter.Application.Contracts.Blog.Article.Commands;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class EditModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        [BindProperty]
        public EditArticle Article { get; set; }
        public List<SelectListItem> ArticleCategories { get; set; }


        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(string id)
        {
            ArticleCategories = _articleCategoryApplication.List().Select(x => new SelectListItem(x.Title, x.Id))
                .ToList();
            Article = _articleApplication.Get(id);

        }

        public RedirectToPageResult OnPost(EditArticle command)
        {
            _articleApplication.Edit(command);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Blog.Article;
using Reter.Application.Contracts.Blog.Article;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetList();
        }

        public RedirectToPageResult OnPostActivate(string id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostRemove(string id)
        {
            _articleApplication.Remove(id);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/CommentManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.Comment;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.CommentManagement
{
    public class ListModel : PageModel
    {
        private readonly ICommentApplication _commentApplication;
        public List<CommentViewModel> Comments;
        public ListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            Comments = _commentApplication.GetComments();
        }

        public RedirectToPageResult OnPostConfirm(string id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostRemove(string id)
        {
            _commentApplication.Delete(id);
            return RedirectToPage("./List");

        }
    }
}

Reter.Presentetion.MVCCore/Pages/Blog/Articles/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.Comment;
using Reter.Application.Contracts.Blog.Comment.Commands;
using Reter.Infrastructure.Query.Blog.Article;

namespace Reter.Presentation.MVCCore.Pages.Blog.Articles
{
    public class DetailModel : PageModel
    {
        public ArticleQueryView Article { get; set; }
        private readonly IArticleView _articleView;
        private readonly ICommentApplication _commentApplication;


        public DetailModel(IArticleView articleView, ICommentApplication commentApplication)
        {
            _articleView = articleView;
            _commentApplication = commentApplication;
        }

        public void OnGet(string id)
        {
            Article = _articleView.GetArticle(id);
        }

        public RedirectToPageResult OnPost(AddComment command)
        {
            _commentApplication.Add(command);
            return RedirectToPage("./detail");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/CommentManagement/List.cshtml
@page
@using Reter.Domain.Blog.CommentAgg
@model Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.CommentManagement.ListModel
@{
    var id = Model.Comments.Count;
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Comment List</h3>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Article</th>
                    <th>Status</th>
                    <th>CreationTime</th>
                    <th>Operations</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var comment in Model.Comments)
                {
                    <tr>

                        <th>@(id--)</th>
                        <th>@comment.Name</th>
                        <th>@comment.Email</th>
                        <th><a asp-page="/blog/articles/detail" asp-route-id="@comment.ArticleId" > @comment.Article </a></th>
                        <th>
                            @if (comment.Status == Statuses.Canceled)
                            {
                                <i class="fa fa-2x fa-close text-danger"></i>
                            }
                            else if (comment.Status == Statuses.Confirm)
                            {
                                <i class="fa fa-2x fa-check text-success"></i>
                            }
                            else
                            {
                                <i class="fa fa-2x fa-eye-slash text-warning"></i>
                            }
                        </th>
                        <th>@comment.CreationTime</th>
                        <th>
                            <a class="btn btn-outline-warning" asp-area="Admin" asp-page="./Edit" asp-route-id="@comment.Id">Show</a>
                            @if (comment.Status == Statuses.New)
                            {
                                <form method="post" asp-page-handler="Confirm" class="float-left mx-2">
                                    <button class="btn btn-outline-success">Confirm</button>
                                    <input name="Id" type="hidden" value="@comment.Id" />
                                </form>

                                <form method="post" asp-page-handler="Remove" class="float-left mx-2">
                                    <button class="btn btn-outline-danger ">Delete</button>
                                    <input name="Id" type="hidden" value="@comment.Id" />
                                </form>
                            }
                            else if (comment.Status == Statuses.Confirm)
                            {
                                <form method="post" asp-page-handler="Remove" class="float-left mx-2">
                                    <button class="btn btn-outline-danger ">Delete</button>
                                    <input name="Id" type="hidden" value="@comment.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Confirm" class="float-left mx-2">
                                    <button class="btn btn-outline-success">Confirm</button>
                                    <input name="Id" type="hidden" value="@comment.Id" />
                                </form>
                            }
                        </th>


                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>