Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Blog.ArticleCategory;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {

        }

        public RedirectToPageResult OnPost(CreateArticleCategory command)
        {
            _articleCategoryApplication.Create(command);
           return RedirectToPage("./list");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.ArticleCategory;
using Reter.Application.Contracts.Blog.ArticleCategory.Commands;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public EditArticleCategory ArticleCategory { get; set; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(string id)
        {
            ArticleCategory = _articleCategoryApplication.Get(id);
        }

        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Edit(ArticleCategory);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/List.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.ArticleCategory;
using Reter.Domain.Blog.ArticleCategoryAgg;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication= articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostRemove(string id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./list");
        }

        public RedirectToPageResult OnPostActivate(string id)
        {
            _articleCategoryApplication.Activate(id);
            return RedirectToPage("./list");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Reter.Application.Contracts.Blog.Article;
using Reter.Application.Contracts.Blog.Article.Commands;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> ArticleCategories { get; set; }

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication,
            IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }


        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List().Select(x => new SelectListItem(x.Title, x.Id))
                .ToList();
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            _articleApplication.Create(command);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Reter.Application.Contracts.Blog.Article;
using Reter.Application.Contracts.Blog.Article.Commands;
using Reter.Application.Contracts.Blog.ArticleCategory;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class EditModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        [BindProperty]
        public EditArticle Article { get; set; }
        public List<SelectListItem> ArticleCategories { get; set; }


        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(string id)
        {
            ArticleCategories = _articleCategoryApplication.List().Select(x => new SelectListItem(x.Title, x.Id))
                .ToList();
            Article = _articleApplication.Get(id);

        }

        public RedirectToPageResult OnPost(EditArticle command)
        {
            _articleApplication.Edit(command);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Blog.Article;
using Reter.Application.Contracts.Blog.Article;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetList();
        }

        public RedirectToPageResult OnPostActivate(string id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostRemove(string id)
        {
            _articleApplication.Remove(id);
            return RedirectToPage("./List");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/CommentManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.Comment;

namespace Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.CommentManagement
{
    public class ListModel : PageModel
    {
        private readonly ICommentApplication _commentApplication;
        public List<CommentViewModel> Comments;
        public ListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            Comments = _commentApplication.GetComments();
        }

        public RedirectToPageResult OnPostConfirm(string id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostRemove(string id)
        {
            _commentApplication.Delete(id);
            return RedirectToPage("./List");

        }
    }
}

Reter.Presentetion.MVCCore/Pages/Blog/Articles/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Reter.Application.Contracts.Blog.Comment;
using Reter.Application.Contracts.Blog.Comment.Commands;
using Reter.Infrastructure.Query.Blog.Article;

namespace Reter.Presentation.MVCCore.Pages.Blog.Articles
{
    public class DetailModel : PageModel
    {
        public ArticleQueryView Article { get; set; }
        private readonly IArticleView _articleView;
        private readonly ICommentApplication _commentApplication;


        public DetailModel(IArticleView articleView, ICommentApplication commentApplication)
        {
            _articleView = articleView;
            _commentApplication = commentApplication;
        }

        public void OnGet(string id)
        {
            Article = _articleView.GetArticle(id);
        }

        public RedirectToPageResult OnPost(AddComment command)
        {
            _commentApplication.Add(command);
            return RedirectToPage("./detail");
        }
    }
}

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Create.cshtml
@page
@model Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement.CreateModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Create New Article Category</h2>
    </div>

    <div class="card-header">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="Title" class="control-label">Title:</label>
                        <input class="form-control" name="Title" id="Title" />
                    </div>
                </div>
                <div class="col-md-12 col-sm-12">
                    <div class="form-group">
                        <label for="Description" class="control-label">Description:</label>
                        <input class="form-control" name="Description" id="Description" />
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a class="btn btn-dark" asp-page="./List" asp-area="Admin">Back To List</a>
                </div>
            </form>
        </div>
    </div>
</div>

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/Edit.cshtml
@page "{id}"
@model Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement.EditModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Edit Article Category</h2>
    </div>

    <div class="card-header">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ArticleCategory.Id"/>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label asp-for="ArticleCategory.Title" class="control-label">Title:</label>
                        <input asp-for="ArticleCategory.Title" class="form-control"   />
                    </div>
                </div>
                <div class="col-md-12 col-sm-12">
                    <div class="form-group">
                        <label asp-for="ArticleCategory.Description" class="control-label">Description:</label>
                        <input asp-for="ArticleCategory.Description" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-warning" />
                    <a class="btn btn-dark" asp-page="./List" asp-area="Admin">Back To List</a>
                </div>
            </form>
        </div>
    </div>
</div>

Reter.Presentetion.MVCCore/Areas/Admin/Pages/Blog/ArticleCategoryManagement/List.cshtml
@page
@model Reter.Presentation.MVCCore.Areas.Admin.Pages.Blog.ArticleCategoryManagement.ListModel
@{
    var id = Model.ArticleCategories.Count;
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article Category List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-area="Admin" asp-page="./Create">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead >
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Description</th>
                <th>Status</th>
                <th>CreationTime</th>
                <th>Operations</th>

            </tr>
            </thead>
            <tbody>

            @foreach (var articleCategory in Model.ArticleCategories)
            {
                <tr>

                    <th>@(id--)</th>
                    <th>@articleCategory.Title</th>
                    <th>@articleCategory.Description</th>
                    <th>
                        @if (@articleCategory.IsDeleted)
                        {
                            <i class="fa fa-2x fa-close text-danger"></i>
                        }
                        else
                        {
                            <i class="fa fa-2x fa-check text-success"></i>
                        }
                    </th>
                    <th>@articleCategory.CreationTime</th>
                    <th>
                        <a class="btn btn-outline-warning" asp-area="Admin" asp-page="./Edit" asp-route-id="@articleCategory.Id">Edit</a>
                        @if (articleCategory.IsDeleted)
                        {
                            <form method="post" asp-page-handler="Activate" class="float-left mx-2">
                                <button class="btn btn-outline-success">Active</button>
                                <input name="Id" type="hidden" value="@articleCategory.Id"/>
                            </form>
                        }
                        else
                        {
                            <form method="post" asp-page-handler="Remove" class="float-left mx-2">
                                <button class="btn btn-outline-danger ">Delete</button>
                                <input name="Id" type="hidden" value="@articleCategory.Id"/>
                            </form>
                        }
                    </th>


                </tr>
            }

            </tbody>
        </table>
    </div>
</div>